oj_svr:oj_server.cpp
	g++ -std=c++11 $^ -o $@ -g -lpthread -I /home/dev/dev/Project/ThirdPartLibForCpp/el7.x86_64/third_part/include -I /usr/include/jsoncpp -L /home/dev/dev/Project/ThirdPartLibForCpp/el7.x86_64/third_part/lib -lctemplate -ljsoncpp
